In [2]:
import csv
import numpy as np
import pandas as pd

## Question 1

In [3]:

file_reader = csv.reader(open("SalaryGender.csv",'r'),delimiter = ",")
salary_col = []
gender_col = []
age_col = []
phd_col = []
first = True
for row in file_reader:
# if we do not need the headings...
#     if first:
#         first=False
#         continue
    salary_col.append(row[0])
    gender_col.append(row[1])
    age_col.append(row[2])
    phd_col.append(row[3])


salary_col = np.array(salary_col)
print(salary_col)
gender_col = np.array(gender_col)
print(gender_col)
age_col = np.array(age_col)
print(age_col)
phd_col = np.array(phd_col)
print(phd_col)
print(len(phd_col),len(gender_col))

['Salary' '140' '30' '35.1' '30' '80' '30' '60' '31.1' '125' '51' '3' '46'
 '150' '3' '130' '15' '130' '84' '190' '74' '73' '10' '50' '7' '9.5'
 '15.2' '28.6' '20' '72' '81' '100' '90' '90' '35' '30' '25' '52' '9' '63'
 '72' '16' '92' '106' '2.5' '9' '32' '32' '55' '52' '28' '20' '14.7'
 '22.3' '34.8' '84' '19' '160' '65' '55' '4.6' '102' '20' '62' '55' '45.6'
 '40' '24' '35' '48' '20' '40.7' '15' '0.25' '152' '39.8' '12' '30' '120'
 '1.7' '36' '96' '38' '90' '9' '25.8' '22' '38.8' '72' '89' '41' '89' '25'
 '52' '115' '66' '18.6' '152' '1.8' '35' '4']
['Gender' '1' '0' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1' '1' '1' '1' '0'
 '1' '0' '1' '1' '0' '0' '0' '0' '0' '1' '1' '0' '0' '1' '0' '0' '0' '1'
 '0' '1' '0' '0' '1' '1' '1' '0' '1' '1' '0' '0' '0' '1' '1' '0' '0' '0'
 '1' '0' '0' '1' '1' '0' '0' '1' '1' '1' '0' '1' '1' '0' '0' '1' '0' '0'
 '0' '1' '0' '1' '0' '0' '1' '1' '1' '1' '1' '0' '1' '1' '0' '0' '0' '1'
 '1' '0' '1' '0' '1' '0' '0' '1' '1' '1' '0' '0']
['Age' '47' '65' '56' '23'

## Question 2

In [4]:
count = 0

# print(len(phd_col),len(gender_col))
gender_col = gender_col[1:]
gender_col = gender_col.astype(int)
phd_col = phd_col[1:]
phd_col = phd_col.astype(int)
data = np.logical_and(gender_col , phd_col)
# print(data)
print(len(phd_col),len(gender_col))
for row in data:
    if row:
        count+=1
print("number of male phds",count)
print("number of wodman phds",len(data)-count)


100 100
number of male phds 24
number of wodman phds 76


## Question3

In [16]:
data = pd.read_csv("SalaryGender.csv")
# print(data)
data = data.drop(["Salary"],axis=1).drop(["Age"],axis=1)
data = data[data.PhD == 1]
print(data)

    Gender  PhD
0        1    1
1        0    1
4        0    1
8        1    1
9        1    1
12       1    1
17       0    1
18       1    1
19       1    1
25       1    1
26       1    1
28       0    1
29       1    1
30       0    1
31       0    1
32       0    1
38       1    1
41       0    1
42       1    1
45       0    1
47       1    1
49       0    1
54       0    1
56       1    1
57       0    1
60       1    1
63       1    1
73       1    1
76       1    1
77       1    1
79       1    1
80       1    1
81       0    1
87       1    1
89       0    1
90       1    1
92       1    1
94       0    1
96       1    1


## Question 4

In [17]:
len(data)

39

## Question 5

In [18]:
arr = [0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]
counter = []
for i in range(0,10):
    counter.append(arr.count(i))
print(counter)

[4, 2, 1, 1, 3, 2, 0, 0, 0, 1]


## Question 6

In [19]:
arr = np.array([[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]])
arr = arr[arr>5]
print(arr)

[ 6  7  8  9 10 11]


## Question 7

In [39]:
arr = np.array([ np.nan, 1., 2., np.nan, 3., 4., 5.])
print(arr[~np.isnan(arr)])

[1. 2. 3. 4. 5.]


## Question 8

In [46]:
arr = np.random.rand(10,10)
print(arr.min())
print(arr.max())

0.006346020524932716
0.9904907778593572


## Question 9

In [50]:
vector = np.random.rand(20)
vector.mean()

0.4687955863982528

## Question 10

In [62]:
arr = np.arange(0,10)
arr = np.concatenate((arr[0:2],-1*arr[3:10]),axis=0)
arr

array([ 0,  1, -3, -4, -5, -6, -7, -8, -9])

## Question 11 Doubt: How to ONLY sort one columns, here all are sorted.

In [70]:
arr = np.random.rand(3,3)
print("before sort\n",arr)
arr.sort(axis=0)
print("after sort\n",arr)


before sort
 [[0.61058141 0.54307012 0.06050171]
 [0.65318947 0.81741693 0.30162241]
 [0.8728179  0.08475891 0.91256517]]
after sort
 [[0.61058141 0.08475891 0.06050171]
 [0.65318947 0.54307012 0.30162241]
 [0.8728179  0.81741693 0.91256517]]


## Question 12

In [78]:
arr = np.random.rand(2,2,2,2)
arr.sum(axis=(2,3))

array([[2.06872265, 0.63983054],
       [0.92967843, 2.54960821]])

## Question 13

In [84]:
arr = np.random.rand(2,2)
print("before swap\n",arr)
temp = arr[0].copy()
arr[0] = arr[1]
arr[1] = temp
print("after swap\n",arr)

before swap
 [[0.11576429 0.85868778]
 [0.65682344 0.78948754]]
after swap
 [[0.65682344 0.78948754]
 [0.11576429 0.85868778]]


## Question 14

In [89]:
arr = np.random.rand(3)
arr = np.linalg.matrix_rank(arr)
arr

1